version: "3.9"

services:
  backend:
    build: ./backend
    container_name: flashsale-backend
    ports:
      - "3020:3020"
    environment:
      - PORT=3020
      - MONGO_URI=mongodb://mongo:27017/flashsale
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    container_name: flashsale-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: flashsale-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo_data:
